[package]
name = "beat_em_up"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "^0.9"
nalgebra = "^0.32"
gilrs = "^0.10"
